export const searchType = {
  samity: {
    name: "samityRegMainTableValue",
    key: [
      "id",
      "by_law",
      "status",
      "purpose",
      "website",
      "email",
      "phone",
      "doptor_id",
      "mobile",
      "office_id",
      "account_no",
      "created_at",
      "created_by",
      "project_id",
      "sold_share",
      "upazila_id",
      "updated_at",
      "updated_by",
      "declaration",
      "district_id",
      "no_of_share",
      "samity_code",
      "samity_name",
      "share_price",
      "account_type",
      "organizer_id",
      "samity_level",
      "account_title",
      "samity_type_id",
      "enterprising_id",
      "member_area_type",
      "working_area_type",
      "certificate_get_by",
      "samity_district_id",
      "samity_division_id",
      "samity_upa_city_id",
      "old_registration_no",
      "member_admission_fee",
      "samity_upa_city_type",
      "samity_formation_date",
      "samity_details_address",
      "samity_uni_thana_paw_id",
      "samity_registration_date",
      "samity_uni_thana_paw_type",
    ],
  },
  budget: "budget",
  committeeMember: "committeeMemberWithPhoto",
  committee: "committeeInfoData",
};
