export const databaseTableKeys = {
  samityRegistrationKeys: [
    "samityCode",
    "samityName",
    "samityLevel",
    "organizerId",
    "officeId",
    "districtId",
    "upazilaId",
    "projectId",
    "samityDivisionId",
    "samityDistrictId",
    "samityUpaCityId",
    "samityUpaCityType",
    "samityUniThanaPawId",
    "samityUniThanaPawType",
    "samityDetailsAddress",
    "samityTypeId",
    "purpose",
    "noOfShare",
    "sharePrice",
    "soldShare",
    "phone",
    "mobile",
    "email",
    "enterprisingId",
    "declaration",
    "memberAreaType",
    "workingAreaType",
    "website",
    "status",
    "doptorId",
    "certificateGetBy",
    "samityFormationDate",
    "oldRegistrationNo",
    "samityRegistrationDate",
    "accountType",
    "accountNo",
    "accountTitle",
    "memberAdmissionFee",
    "createdBy",
    "createdAt",
    "updatedBy",
    "updatedAt",
    "byLaw",
    // "approveBy",
  ],
  samityTransactionKeys: [
    "tranId",
    "samityId",
    "glacId",
    "orpCode",
    "tranDate",
    "incAmt",
    "expAmt",
    "financialYear",
    "isIeBudget",
    "remarks",
    "status",
    "budgetRole",
    "createdBy",
    "created",
    "updatedBy",
    "updatedAt",
    "approveBy",
  ],
  memberRegistrationInfo: [
    "member_code",
    "samity_id",
    "nid",
    "brn",
    "dob",
    "member_name",
    "member_name_bangla",
    "father_name",
    "mother_name",
    "spouse_name",
    "gender_id",
    "education_level_id",
    "occupation_id",
    "marital_status_id",
    "mobile",
    "email",
    "committee_organizer",
    "committee_contact_person",
    "committee_signatory_person",
    "member_photo",
    "member_sign",
    "documents",
    "ref_samity_id",
    "member_admission_date",
    "created_by",
    "created_at",
    "updated_by",
    "updated_at",
    "doptor_id",
    "is_active",
    "religion_id",
  ],

  memberAddressInfo: [
    "samity_id",
    "member_id",
    "address_type",
    "district_id",
    "upa_city_id",
    "upa_city_type",
    "uni_thana_paw_id",
    "uni_thana_paw_Type",
    "details_address",
    "created_by ",
    "created_at",
    "updated_by ",
    "updated_at",
  ],

  workingArea: [
    "samity_id",
    "division_id",
    "district_id",
    "upa_city_id",
    "upa_city_type",
    "uni_thana_paw_id",
    "uni_thana_paw_Type",
    "status",
    "details_address",
    "created_by",
    "created_at",
    "updated_by",
    "updated_at",
  ],

  memberArea: [
    "samity_id",
    "division_id",
    "district_id",
    "upa_city_id",
    "upa_city_type",
    "uni_thana_paw_id",
    "uni_thana_paw_Type",
    "status",
    "details_address",
    "created_by",
    "created_at",
    "updated_by",
    "updated_at",
  ],

  memberFinancial: [
    "member_id",
    "samity_id",
    "no_of_share",
    "share_amount",
    "savings_amount",
    "loan_outstanding",
    "created_by",
    "created_at",
    "updated_by",
    "updated_at",
  ],

  committeeInfo: [
    "samity_id",
    "committee_type",
    "election_date",
    "effect_date",
    "duration",
    "no_of_member",
    "expire_date",
    "status",
    "meeting_date",
    "attachment",
    "doptor_id",
    "created_by",
    "created_at",
    "updated_by",
    "updated_at",
  ],

  committeeMemberInfo: [
    "committee_id",
    "samity_id",
    "committee_type",
    "member_id",
    "is_member",
    "member_name",
    "org_name",
    "mobile",
    "committee_role_id",
    "nid",
    "dob",
    "status",
    "created_by",
    "created_at",
    "updated_by",
    "updated_at",
  ],

  samityTransaction: [
    "is_ie_budget",
    "financial_year",
    "samity_id",
    "glac_id",
    "orp_code",
    "tran_date",
    "inc_amt",
    "exp_amt",
    "remarks",
    "status",
    "budget_role",
    "created_by",
    "created_at",
    "updated_by",
    "updated_at",
  ],

  samityDocument: [
    "samity_id",
    "document_id",
    "document_name",
    "document_no",
    "effect_date",
    "expire_date",
    "created_by",
    "created_at",
    "updated_by",
    "updated_at",
  ],

  applicationArchive: [
    "id",
    "samityId",
    "serviceId",
    "nextAppDesignationId",
    "finalApprove",
    "status",
    "data",
    "shiftedAt",
    "createdBy",
    "createdAt",
    "updatedBy",
    "updatedAt",
  ],
  applicationApprovalArchive: [
    "id",
    "userId",
    "applicationId",
    "remarks",
    "actionDate",
    "serviceActionId",
    "originUnitId",
    "officeId",
    "designationId",
    "employeeId",
    "attachment",
    "shiftedAt",
    "createdBy",
    "createdAt",
    "updatedBy",
    "updatedAt",
  ],

  budget: [
    "samityId",
    "startYear",
    "endYear",
    "glacId",
    "amount",
    "createdBy",
    "createdAt",
    "updatedBy",
    "updatedAt",
  ],
  glTrans: [
    "samityId",
    "glacId",
    "tranDate",
    "tranAmount",
    "drCrCode",
    "remarks",
    "status",
    "createdBy",
    "createdAt",
    "updatedBy",
    "updatedAt",
  ],
};
